---
title: "utdt_consigna2"
author: "icalb"
date: '2022-08-24'
output: html_document
---


```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(sf)
```

```{r}
base_properati_2020.2021 <-read.csv("data/amba_properati_2020-2021.csv", stringsAsFactors = TRUE)
```

```{r}
properati_venta <- base_properati_2020.2021 %>% 
  filter(str_detect(string = operation_type , 
                    pattern = "Venta"))
```
```{r}
properati_venta_usd <- properati_venta %>% 
  filter(str_detect(string = currency ,
                      pattern = "USD"))

```

```{r}
install.packages("datos")
library(datos)
```

```{r}
Agrupados_properati_venta_usd_1 <- properati_venta_usd 
```

```{r}
Agrupados_properati_venta_usd_1 <- properati_venta_usd %>%
  group_by (partido) %>%
  summarise(ofertausd = sum(price))
```

```{r}
Agrupados_properati_venta_usd_1<-  
filter(Agrupados_properati_venta_usd_1, partido !="Capital Federal")
```


```{r}
ggplot(data=Agrupados_properati_venta_usd_1, aes( x=ofertausd, y=partido)) + 
    geom_bar(stat="identity", position="dodge") 
```

```{r}
partidos_amba <- st_read("data/partidos_amba.geojson")
```


```{r}
  ggplot(partidos_amba)+
  geom_sf()
```
```{r}
amba_properati_2021 <-read.csv("data/amba_properati2021.csv" , stringsAsFactors = TRUE)
```


```{r}
ggplot()+
  geom_sf(data=partidos_amba)+
  geom_point(data=amba_properati_2021, aes(x=lon, y=lat, color=provincia))
```

```{r}
ggplot()+
  geom_sf(data=partidos_amba)+
  geom_bin2d(data = amba_properati_2021, aes(x = lon, y = lat), alpha=0.75, bins=50)+
  labs(title="Densidad de publicaciones",
       fill="Cantidad")+
  scale_fill_viridis_c()
```

